### ISSUE TITLE
Feat: connect chat server

### ISSUE THREAD

**Issue by mkngkm** [Hanaro-OMNM/Hanasset-FE-Consultant#2]
## Description

- 채팅 서버 상담사 페이지 임시 연결
- 상담 대기 리스트 api 호출
- 상담 status 업데이트 => 채팅 활성화

## Estimated Duration

12/22(일) ~ 12/23 (월) [2일]

## Classification

- [x] 기능
- [ ] 버그
- [ ] 기타

## TO-DO

- [ ] 상담 대기 리스트 api 호출
- [ ] 상담 status 업데이트
- [ ] active 채팅 활성화
